SCENARIOS = [
 {'resultats': {'NFN': 10}, 'prescription': ['A','B','C']},
 {'resultats': {'NFN': 1}, 'prescription': ['A','B','C']},
]
# Autogenerated with DRAKON Editor 1.11

def regle1(demande):
    #item 16
    if valeur('NFN') > 5:
        pass
    else:
        #item 20
        repasser('A','B')
        #item 19
        declencher_tests('Z','Y')
    #item 15
    valider_resultat('NFN')


